name: Run Databricks Job on Approval or Rejection

on:
  workflow_dispatch:
    inputs:
      decision:
        description: "Approval decision"
        required: true
        type: choice
        options:
          - approve
          - reject

jobs:
  handle-decision:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "DATABRICKS_HOST=https://adb-2376768479807879.19.azuredatabricks.net" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=dose866835cb24a4eb9ca3ad5f7782f25533" >> $GITHUB_ENV

      - name: Trigger Databricks Job with Approval Status
        run: |
          curl -X POST https://$DATABRICKS_HOST/api/2.1/jobs/run-now \
            -H "Authorization: Bearer $DATABRICKS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "job_id": 970491915739877,
              "notebook_params": {
                "status": "${{ github.event.inputs.decision }}"
              }
            }'
